# Generated by Django 6.0.2 on 2026-03-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=100)),
                ('sensor', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'lecturas',
                'ordering': ['-fecha'],
            },
        ),
    ]
