# Generated by Django 6.0.2 on 2026-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='estacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='sensor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
