# Generated by Django 6.0.2 on 2026-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0002_alter_lectura_estacion_alter_lectura_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='estacion',
            field=models.CharField(max_length=50),
        ),
    ]
