# Generated by Django 6.0.2 on 2026-04-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0003_alter_lectura_estacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='estacion',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='fecha',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lectura',
            index=models.Index(fields=['estacion', '-fecha'], name='lecturas_estacio_7e235d_idx'),
        ),
    ]
